Restructure build system
linux-minidisc/linux-minidisc pull request #21
Opened 2016-09-29 22:09 UTC by thp

This pull request is split off from #10 and contains only the build system changes that will later on enable the Continous Integration builds on Travis CI.

2016-09-29 23:28 UTC, karcherm commented
This pull request does not only contain build system changes, but also changes the include directives in qhimdwindetection.cpp. It seems these changes are appropriate if you use the original Microsoft header files. When that file was written, the subdirectory "ddk" was indeed needed if you (cross-)compile with mingw using the header files mingw provides.
Did that change in the mean time?

2016-10-02 08:13 UTC, thp commented
I needed to do that change so that it compiles in Ubuntu (as on Travis CI) with Mingw-W64 (which is a fork of mingw32 with support for both 32- and 64-bit). I didn't test that change with Windows compilers, though.

Here's the build logs for building with 32- and 64-bit versions of Mingw-W64 with that code change:

https://travis-ci.org/thp/linux-minidisc/jobs/163859833
https://travis-ci.org/thp/linux-minidisc/jobs/163859831

2016-10-09 12:00 UTC, thp commented
If you really want, I can split out the changes to `qhimdtransfer/qhimdwindetection.cpp` to a separate pull request, just let me know if there's anything left to do here or if this can be merged.

2016-10-15 18:52 UTC, thp commented
*bump* - what's the status here, should I separate out the .cpp changes into a separate pull request or can we merge this as-is?

2016-11-27 19:21 UTC, glaubitz commented
Yes, those should go into a different commit, please.

2016-12-01 11:05 UTC, thp commented
Spilt off into https://github.com/glaubitz/linux-minidisc/pull/22 and rebased this one on top of it.

2016-12-01 11:06 UTC, thp commented
Merge after #22.

2016-12-01 22:02 UTC, glaubitz requested changes

2016-12-01 22:02 UTC, glaubitz commented on qhimdtransfer/qhimdwindetection.cpp
> +#include <cfgmgr32.h>   // needed for CM_Get_Child function
Why is this still in here? Wasn't this supposed to be in #22?

2016-12-01 22:02 UTC, glaubitz commented on build/libgcrypt.pri
> +else: !build_pass: message(You disabled mcrypt: No PCM and ATRAC transfer will be supported)
The message should mention "gcrypt", not "mcrypt". mcrypt was dropped in c5a16774418f25ff30089589c8249d3708c8335c.

2016-12-01 22:04 UTC, glaubitz commented on qhimdtransfer/qhimdwindetection.cpp
> +#include <cfgmgr32.h>   // needed for CM_Get_Child function
Ok, this change doesn't show up in the other view. Strange.

2016-12-01 22:09 UTC, merged