added netmd download support in netmdcli
linux-minidisc/linux-minidisc pull request #27
Opened 2016-12-21 00:00 UTC by tharp

I added netmd download support in netmdcli.
Supported formats are: 16bit pcm @ 44k1Hz stereo or mono and Atrac LP2/4 stored in a wav container file.

As i tested, bitrate conversion ( pcm -> Atrac LP2/4) doesn´t work this way, transfer is fine but no audio output when playing the track. Also pcm stereo -> Atrac SP mono failed with unknown error.
So i left it the way i worked on before:
16bit pcm mono -> Atrac SP mono
16bit pcm stereo -> Atrac SP stereo
LP2 -> LP2
LP4 -> LP4

Also added some more detailed debug messages, may be very useful when testing/debugging.

Successfully tested with different stereo pcm and LP2 files, LP4 and mono not tested, yet.

2016-12-21 10:43 UTC, thp requested changes
Still needs some work, but a nice feature to be added.

2016-12-21 10:43 UTC, thp commented on libnetmd/secure.c
> +        error = libusb_bulk_transfer((libusb_device_handle*)dev, 2, packet, (int)packet_size, &transferred, 80000);
Should the timeout be somehow dependent on the `packet_size`? Or asked the other way around: For which maximum file size is 80000 a good value? Can I upload a single 2-hour-track with this?

2016-12-21 10:43 UTC, thp commented on libnetmd/secure.c
> +        if ((chunksize % frame_size) != 0) {
This can be rewritten without a condition:

```
chunksize = ((chunksize + frame_size - 1) / frame_size) * frame_size;
```

2016-12-21 10:43 UTC, thp commented on netmdcli/netmdcli.c
> +        if(leword16(file+32) == 384) {                       /* data block size LP2 */
Maybe make 384 and 192 a constant `NETMD_DATA_BLOCK_SIZE_LP2` and `NETMD_DATA_BLOCK_SIZE_LP4`?

2016-12-21 10:43 UTC, thp commented on netmdcli/netmdcli.c
> +    return c[3]*16777216+c[2]*65536+c[1]*256+c[0];
Maybe easier to read:

```
return (c[3] << 24) + (c[2] << 16) + (c[1] << 8) + c[0];
```

2016-12-21 10:43 UTC, thp commented on netmdcli/netmdcli.c
> +static int wav_data_position(const unsigned char * data, size_t len)
Is it possible to make that less fragile by parsing the WAV file header if possible and looking for the audio data offset that way and not scanning for the string "data"? What if some of the header fields by chance contain "data"?

2016-12-21 10:43 UTC, thp commented on netmdcli/netmdcli.c
> +    while(pos < 0)
The first conditional-break can be moved into the while condition, and it's actually better to use `break` when pos is set than checking for `pos < 0` in every iteration):

```
while (i < len - 4) {
    if (strncmp(...) {
        pos = i;
        break;
    }
    i += 2;
}
```

2016-12-21 10:43 UTC, thp commented on netmdcli/netmdcli.c
> +    if(strncmp("RIFF", file, 4) != 0 || strncmp("WAVE", file+8, 4) != 0 || strncmp("fmt ", file+12, 4) != 0)
This probably also needs to get the size of the data in `file` as argument and then check that the size is greater than the maximum offset we're reading here and below, otherwise we're reading out of bounds.

2016-12-21 10:43 UTC, thp commented on netmdcli/netmdcli.c
> +                    puts("reading file: stat o.k.");
The debug output here and below should probably be made conditional with some macro?

2016-12-21 10:43 UTC, thp commented on netmdcli/netmdcli.c
> +                    if(data == NULL) puts("error allocating memory for file input");
Would need to clean up here and/or break in case we can't allocate memory, right now this just continues below with the invalid pointer (`fread(data, data_size, 1, f);`).

2016-12-21 10:43 UTC, thp commented on netmdcli/netmdcli.c
> +                    else puts("audio file unknown or not supported");
Again, if it's unsupported, we probably need to break out and clean up and not continue.

2016-12-21 19:05 UTC, tharp commented on libnetmd/secure.c
> +        error = libusb_bulk_transfer((libusb_device_handle*)dev, 2, packet, (int)packet_size, &transferred, 80000);
On my tests , some time ago, i just played around with the tiimeout for a "normal length" track of 4 - 5 minutes. My current test wav file has 16MB (1:31 min) and needs round about 27 seconds for packet transfer. I think a safe value could be 20 sec/minute (pcm stereo) or 2 sec / 1MB packet size. I´ve tested witk my RH1, i don´t know if other/older devices are slower.

Afaik the largest minidiscs are 80 min., i didn´t transfer a 80 min track yet. Maybe it is worth a test with 1600 sec timeout (20 sec/min).

2016-12-21 19:07 UTC, tharp commented on netmdcli/netmdcli.c
> +    return c[3]*16777216+c[2]*65536+c[1]*256+c[0];
I just used these functions 1:1 as we use it in libhimd/qhimdtransfer.

2016-12-21 19:18 UTC, tharp commented on netmdcli/netmdcli.c
> +static int wav_data_position(const unsigned char * data, size_t len)
O.K., good point. Possibly a wave file could have more chunks as just the standard "riff" and "data" chunks. Maybe we can use a combination of both. Every chunk stores its chunksize, so we could jump to the next chunk and then check if it´s the data chunk.

2016-12-21 19:20 UTC, tharp commented on netmdcli/netmdcli.c
> +    if(strncmp("RIFF", file, 4) != 0 || strncmp("WAVE", file+8, 4) != 0 || strncmp("fmt ", file+12, 4) != 0)
O.K., good point.

2016-12-21 19:27 UTC, tharp commented on netmdcli/netmdcli.c
> +        if(leword16(file+32) == 384) {                       /* data block size LP2 */
In addition to that, i think we are also missing the framesize for mono pcm in netmd_get_framesize(). Mono transfers should not work in the  current version, but, as i said, i´ve not tested mono.

2016-12-21 19:29 UTC, tharp commented on netmdcli/netmdcli.c
> +                    puts("reading file: stat o.k.");
Maybe we could use netmd_log() function with level NETMD_LOG_DEBUG.

2016-12-21 19:40 UTC, tharp commented on netmdcli/netmdcli.c
> +                    else puts("audio file unknown or not supported");
Yes, you´re right, i just expanded the existing "send" routine but forgot to add some "break on error" parts. This is also missing in the current version.

2016-12-24 23:38 UTC, glaubitz commented
@tharp Please reformat and rewrite your commit messages. The first line should contain a short summary without a full stop and no longer than ~65 columns. Use the present tense and proper capitalization.

Additional description may be added in a block paragraph starting from the third line, the second line remains blank.

This is the usual formatting style for commit messages used by most open source projects.

2016-12-25 15:49 UTC, tharp commented
can be closed without merging, see pull request #28

2016-12-25 19:42 UTC, thp commented
Closing as per the latest comment, let's continue the discussion in #28 (note that you could also force-push the rebased commits onto your pull request branch to have the pull request updated, but whatever works for you).

2016-12-25 19:42 UTC, closed without merging